version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7-node-browsers-legacy
    steps:
    - checkout
    - run:
        name: Get yapf
        command: pip install yapf && export PATH=$PATH:$HOME/.local/bin
    - run:
        name: Python style check (yapf diff)
        command: python tools/testing/check_yapf.py --path=clarify
workflows:
  version: 2
  workflow:
    jobs:
    - build

