name: Deploy models to KFServing
on:
  push:
    branches:
    - master
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy a custom kfserving container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: |
        gcloud auth configure-docker
    - name: Build KFServing custom runtime image
      run: |
        docker build -t gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
    - name: Publish the custome kfserving image
      run: |
        docker push gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
    - name: Get kubernetes credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE --project $GKE_PROJECT
    - name: Create inference service
      run: |
        echo 'todo'

